namespace: fleet-mc-helm-example
targetCustomizations:
- name: test
  helm:
    values:
      replication: false
  clusterSelector:
    matchLabels:
      env: test

- name: prod
  helm:
    values:
      replicas: 0
  clusterSelector:
    matchLabels:
      name: local
